name: OrangeFox - Build RMX1901

on:
  workflow_dispatch:

jobs:
  build:
    name: Build OFRP for RMX1901
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Clean-up
      uses: rokibhasansagar/slimhub_actions@v25.42.5

    - name: Swap Space
      uses: pierotofy/set-swap-space@v1.0
      with:
        swap-size-gb: 24

    - name: Build Environment & Dependencies
      run: |
        sudo apt-get update -y && sudo apt-get upgrade -y
        sudo apt-get install git aria2 ccache openjdk-8-jdk -y
        
        git clone https://gitlab.com/OrangeFox/misc/scripts --depth=1
        cd scripts       
        sudo bash setup/android_build_env.sh
        
        # Set environment variables locally to prevent sdkmanager & cd - crashes
        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
        export PATH=$JAVA_HOME/bin:$PATH
        export OLDPWD="$(pwd)"
        
        # Run SDK setup without sudo
        bash setup/install_android_sdk.sh

    - name: Set-up Manifest & Sync Source
      run: |
        mkdir -p ${GITHUB_WORKSPACE}/OrangeFox
        cd ${GITHUB_WORKSPACE}/OrangeFox
        git config --global user.name "ij-israfil"
        git config --global user.email "israfilkhan494@gmail.com"
        git clone https://gitlab.com/OrangeFox/sync.git --depth=1
        cd sync
        ./orangefox_sync.sh --branch 12.1 --path ${GITHUB_WORKSPACE}/OrangeFox/fox_12.1

    - name: Clone Device Tree
      run: |
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_12.1
        git clone https://github.com/ij-israfil/recovery_realme_RMX1901 -b ofox device/realme/RMX1901

    - name: Setup CCache
      run: |
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_12.1
        export USE_CCACHE=1
        export CCACHE_EXEC=/usr/bin/ccache
        export CCACHE_DIR=${GITHUB_WORKSPACE}/OrangeFox/fox_12.1/.ccache
        ccache -M 10G

    - name: Building OrangeFox
      run: |
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_12.1
        export ALLOW_MISSING_DEPENDENCIES=true
        export USE_CCACHE=1
        export CCACHE_EXEC=/usr/bin/ccache
        export CCACHE_DIR=${GITHUB_WORKSPACE}/OrangeFox/fox_12.1/.ccache
        
        source build/envsetup.sh
        lunch twrp_RMX1901-eng
        mka adbd recoveryimage -j$(nproc --all)

    - name: Upload Recovery Artifacts (GitHub)
      uses: actions/upload-artifact@v4
      with:
        name: OrangeFox-RMX1901-Recovery
        path: |
          ${{ github.workspace }}/OrangeFox/fox_12.1/out/target/product/RMX1901/Orange*.zip
          ${{ github.workspace }}/OrangeFox/fox_12.1/out/target/product/RMX1901/recovery.img
        retention-days: 7

    - name: Upload Recovery via Gofile
      run: |
        sudo wget https://raw.githubusercontent.com/ij-project/gofile-uploader/refs/heads/master/gofile -O "/usr/local/bin/gofile"
        sudo chmod +x "/usr/local/bin/gofile"
        
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_12.1/out/target/product/RMX1901
        gofile Orange*.zip
        
